@startmindmap

* root
** 244577237 org.huberb:tgftools:jar:1.0-SNAPSHOT
*** 1612496268 info.picocli:picocli:jar:4.6.1:compile
*** 13692003 org.junit.jupiter:junit-jupiter-api:jar:5.8.1:test
*** 94748968 org.opentest4j:opentest4j:jar:1.2.0:test
*** 1944815218 org.junit.platform:junit-platform-commons:jar:1.8.1:test
*** 1497558532 org.apiguardian:apiguardian-api:jar:1.1.2:test
*** 1584833211 org.junit.jupiter:junit-jupiter-params:jar:5.8.1:test
*** 1970377948 org.junit.jupiter:junit-jupiter-engine:jar:5.8.1:test
*** 1518752790 org.junit.platform:junit-platform-engine:jar:1.8.1:test

@endmindmap

